[phases.setup]
commands = [
  "python3 -m venv venv",
  ". venv/bin/activate"
]

[phases.install]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"
]

[metadata]
name = "ytmp3-server"

