[phases.setup]
commands = [
  "apt-get update",
  "apt-get install -y ffmpeg"
]

[phases.install]
commands = [
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"
]

[metadata]
name = "ytmp3-server"
