[phases.setup]
commands = [
  "python3 -m venv venv"
]

[phases.install]
commands = [
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
commands = [
  "./venv/bin/gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"
]

[metadata]
name = "ytmp3-server"
