[phases.setup]
nixPkgs = ["python312", "ffmpeg", "git", "curl"]

[phases.install]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"

[metadata]
name = "ytmp3-server"
