[phases.setup]
commands = [
  "python3 -m venv venv"
]

[phases.install]
commands = [
  "./venv/bin/pip install --upgrade pip",
  "./venv/bin/pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
cmd = "./venv/bin/gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"

