[phases.setup]
nixPkgs = [
  "python312",
  "python3Packages.yt-dlp",
  "python3Packages.flask",
  "python3Packages.gunicorn",
  "ffmpeg"
]

[phases.install]
commands = [
  # Deploy başında pip cache'i temizle ki eskiden kalan paketler hata vermesin
  "rm -rf /root/.cache/pip",
  "echo 'Pip cache temizlendi.'"
]

[phases.build]
commands = []

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"

[metadata]
name = "ytmp3-server"

