[phases.setup]
commands = [
  "python3 -m venv venv",
  ". venv/bin/activate"
]

[phases.install]
commands = [
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "python ytmp3_server.py"
]

[metadata]
name = "ytmp3-server"
