[phases.setup]
nixPkgs = ["python312", "ffmpeg"]

[phases.install]
commands = [
  "python3 -m ensurepip --upgrade",      # pip'i aktif et
  "python3 -m pip install --upgrade pip", 
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT ytmp3_server:app"

[metadata]
name = "ytmp3-server"

